Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2020-10, with the labels that each got.

#8212 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8223 Add Zaheer Abbas
  CONTRIBUTORS.md
Labels: Conflict Present

#8229 Added taepal467 to the contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8248 Add JigsKapadia
  CONTRIBUTORS.md
Labels: Conflict Present

#8273 Added my name to the contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8270 added mrashduke to list
  CONTRIBUTORS.md
Labels: Conflict Present

#8260 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8282 Added hmbjorkevoll to contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8313 ADD sandeep-chahal
  CONTRIBUTORS.md
Labels: Conflict Present

#8323 Add cessycode as contributor
  CONTRIBUTORS.md
Labels: Conflict Present

#8324 Added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8372 Add my name to contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8454 added my name to contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8488 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8507 added my name to the contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8555 added name to list
  CONTRIBUTORS.md
Labels: Conflict Present

#8579 added name to list of contributors
  CONTRIBUTORS.md
Labels: Conflict Present

#8582 adding my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8589 Test
  CONTRIBUTORS.md
Labels: Conflict Present

#8616 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8643 add aronakhmad
  CONTRIBUTORS.md
Labels: Stale

#8654 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8662 added my name to contributors list
  CONTRIBUTORS.md
Labels: Conflict Present

#8664 Just add my name
  CONTRIBUTORS.md
Labels: Conflict Present

#8666 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present
