Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2020-12, with the labels that each got.

#10006 contribiton PR
  CONTRIBUTORS.md
Labels: Conflict Present

#10025 added my name to the list of contributors
  CONTRIBUTORS.md
Labels: Stale

#10026 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#10029 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#10100 Add @juppsy
  CONTRIBUTORS.md
Labels: bug

#10092 added name to contributor list
  CONTRIBUTORS.md
Labels: bug

#10224 added my name to contributer list
  CONTRIBUTORS.md
Labels: Stale

#10214 add my name to the organization
  .archive/CONTRIBUTORS.archived.DO.NOT.EDIT.md
Labels: Stale

#10219 Adding my name to the contributors list
  CONTRIBUTORS.md
Labels: Stale
