Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2020-11, with the labels that each got.

#8674 Added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8680 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8682 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8684 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8690 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#8679 Added @ehsanulhaq001 to contribution list
  CONTRIBUTORS.md
Labels: bug

#8830 I have added my name to contributer list
  CONTRIBUTORS.md
Labels: Stale

#8850 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: Stale

#8854 new contributor name added
  CONTRIBUTORS.md
Labels: Stale

#8855 added my name to the contributor list
  CONTRIBUTORS.md
Labels: Stale

#8860 Fixed other users styling, added my self
  CONTRIBUTORS.md
Labels: Stale

#8913 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#8924 add name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#8929 i just added my git acc
  CONTRIBUTORS.md
Labels: Stale

#8931 i just added my git acc
  CONTRIBUTORS.md
Labels: Stale

#8946 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#8954 add my name
  CONTRIBUTORS.md
Labels: Stale

#8955 Add as contributor. Fixed 2 other links
  CONTRIBUTORS.md
Labels: Stale

#9024 I've added my name to the Contributor List
  CONTRIBUTORS.md
Labels: Stale

#9025 Add farhaddashtia to Contributors list
  CONTRIBUTORS.md
Labels: Stale
