Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-01, with the labels that each got.

#10437 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#10592 added my name to the list
  CONTRIBUTORS.md
Labels: bug

#10692 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale
