Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-04, with the labels that each got.

#11497 Added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#11509 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#11512 Added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#11520 add name to CONTRIBUTORS
  CONTRIBUTORS.md
Labels: Stale

#11496 added my name to the contributors list
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#11522 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#11542 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#11569 finally my name is added to the list thanks Sir Neagoie
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#11623 Contribute List
  CONTRIBUTORS.md
Labels: Stale

#11625 Added my name to contributors list
  CONTRIBUTORS.md
Labels: Stale

#11738 Added myself to contributors
  CONTRIBUTORS.md
Labels: Conflict Present, Stale
