Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-06, with the labels that each got.

#12127 added name to contributors list
  CONTRIBUTORS.md
Labels: Stale

#12210 Added my name
  CONTRIBUTORS.md
Labels: Conflict Present, Stale

#12133 Add GabrielOAvila
  CONTRIBUTORS.md
Labels: Conflict Present, bug

#12259 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#12264 added my name
  CONTRIBUTORS.md
Labels: Conflict Present

#12268 Test
  CONTRIBUTORS.md
Labels: Conflict Present

#12271 Added my name, formatted two names above me
  CONTRIBUTORS.md
Labels: Conflict Present

#12272 added my name to contributors.md
  CONTRIBUTORS.md
Labels: invalid

#12273 added name to list
  CONTRIBUTORS.md
Labels: Conflict Present

#12309 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#12319 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#12347 added my name to contibutor list
  CONTRIBUTORS.md
Labels: Conflict Present

#12351 my name to contributors list
  CONTRIBUTORS.md
Labels: Conflict Present
