Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-10, with the labels that each got.

#13439 Rajul branch
  CONTRIBUTORS.md
Labels: bug

#13236 My
  .github/stale.yml
  .github/workflows/run-sort-users-script.yml
  CONTRIBUTORS.md
  sort-users.py
Labels: invalid

#13356 Added my name to the list
  CONTRIBUTORS.md
Labels: Stale

#13507 added my name to contributor list.
  CONTRIBUTORS.md
Labels: Conflict Present
