Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-02, with the labels that each got.

#10906 Added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#10913 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#10916 Add Karthik-Nayak98 to contributors list
  CONTRIBUTORS.md
Labels: bug

#10995 added my name to the contributers list
  CONTRIBUTORS.md
Labels: Stale

#11002 Added my name to the contributors list
  CONTRIBUTORS.md
Labels: Stale

#11036 added my name to the contributor list
  CONTRIBUTORS.md
Labels: Stale

#11027 added username and cleanup
  CONTRIBUTORS.md
Labels: Conflict Present

#11049 added my name to the list
  CONTRIBUTORS.md
Labels: Stale

#11057 added my name to the contributors list
  CONTRIBUTORS.md
Labels: Stale
