Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2021-05, with the labels that each got.

#11798 my name
  CONTRIBUTORS.md
Labels: Stale

#11805 added windycy to contributor list
  CONTRIBUTORS.md
Labels: Stale

#11811 added name to contribution file
  CONTRIBUTORS.md
Labels: Stale

#11834 adding my name to the contributer List
  CONTRIBUTORS.md
Labels: Stale

#11837 added my name to contributors and fixed prev user
  CONTRIBUTORS.md
Labels: Stale

#11839 Adding name to contributors
  CONTRIBUTORS.md
Labels: Stale

#11950 Add krissylegaspi
  CONTRIBUTORS.md
Labels: Stale

#11960 Add AbubakarShf to contribution list
  CONTRIBUTORS.md
Labels: bug

#12008 Pedro
  CONTRIBUTORS.md
Labels: Stale

#12009 Add EagleAngelo
  CONTRIBUTORS.md
Labels: Stale

#12010 added my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#11999 Added my name to the contributors list
  CONTRIBUTORS.md
Labels: Stale

#12071 added my name
  CONTRIBUTORS.md
Labels: Stale

#12119 added my name to contributorlist
  CONTRIBUTORS.md
Labels: Conflict Present
