Repository zero-to-mastery/start-here-guidelines, pull requests merged in 2023-01, with the labels that each got.

#17925 Add my @beeburrt
  CONTRIBUTORS.md
Labels: Stale

#18103 added my name to contributor list
  CONTRIBUTORS_OLD.md
Labels: Stale

#18086 added my name to the contributer list
  CONTRIBUTORS_OLD.md
Labels: Conflict Present, Stale

#18168 Test
  CONTRIBUTORS.md
  CONTRIBUTORS_OLD.md
Labels: Stale

#18177 Add my name to contributor list
  CONTRIBUTORS.md
Labels: Stale

#18186 Add presianrusinov
  CONTRIBUTORS.md
Labels: Conflict Present

#18198 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#18278 Add contributor
  CONTRIBUTORS.md
  GitnGitHub-CLI.docx
  GitnGitHub.docx
  ~$tnGitHub-CLI.docx
Labels: Conflict Present

#18307 Added my name to the list
  CONTRIBUTORS.md
Labels: Conflict Present

#18357 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present

#18420 added my name to contributor list
  CONTRIBUTORS.md
Labels: Conflict Present
